apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour-app
  template:
    metadata:
      labels:
        app: tour-app
    spec:
      containers:
      - name: tour-app
        image: 010426082127.dkr.ecr.us-east-1.amazonaws.com/dotnet-project:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tour-app-service
spec:
  type: LoadBalancer
  selector:
    app: tour-app
  ports:
  - port: 80
    targetPort: 80
