apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-management-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour-management
  template:
    metadata:
      labels:
        app: tour-management
    spec:
      containers:
      - name: tour-management
        image: 010426082127.dkr.ecr.us-east-1.amazonaws.com/dotnet-project:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tour-management-service
spec:
  selector:
    app: tour-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
