//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tour_Management
{
    public partial class AdminProfile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;
        protected global::System.Web.UI.WebControls.GridView GridViewBookings;
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceBookings;
    }
}
