# Use Microsoft ASP.NET runtime image
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019

# Set working directory
WORKDIR /inetpub/wwwroot

# Copy all project files
COPY . .

# Expose port
EXPOSE 80
