<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="mybooking.aspx.cs" Inherits="Tour_Management.mybooking" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Your Current Bookings</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7f7f7;
        }
        h1 {
            text-align: center;
            margin-top: 30px;
            color: #333;
        }
        .grid-container {
            display: flex;
            justify-content: center;
            margin-top: 40px;
        }
    </style>
</head>
<body>
    <h1>YOUR CURRENT BOOKINGS</h1>
    <div class="grid-container">
        <form id="form1" runat="server">
            <asp:GridView 
                ID="GridView1" 
                runat="server" 
                AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True"
                DataSourceID="SqlDataSource1"
                DataKeyNames="BookingId"
                Width="800px"
                BackColor="White" 
                BorderColor="#DEDFDE" 
                BorderStyle="None"
                BorderWidth="1px" 
                CellPadding="4" 
                ForeColor="Black" 
                GridLines="Vertical">

                <AlternatingRowStyle BackColor="#F7F7DE" />
                <HeaderStyle BackColor="#6B696B" Font-Bold="True" ForeColor="White" />
                <RowStyle BackColor="#FFFFFF" HorizontalAlign="Center" />
                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />

                <Columns>
                    <asp:BoundField DataField="BookingId" HeaderText="Booking ID" ReadOnly="True" />
                    <asp:BoundField DataField="TOUR_NAME" HeaderText="Tour Name" />
                    <asp:BoundField DataField="PLACE" HeaderText="Place" />
                    <asp:BoundField DataField="Email" HeaderText="Email" />
                    <asp:BoundField DataField="FirstName" HeaderText="First Name" />
                </Columns>
            </asp:GridView>

            <asp:SqlDataSource 
                ID="SqlDataSource1" 
                runat="server"
                ConnectionString="<%$ ConnectionStrings:dbconnection %>"
                SelectCommand="SELECT BookingId, TOUR_NAME, PLACE, Email, FirstName FROM booking"
                DeleteCommand="DELETE FROM booking WHERE BookingId=@BookingId">
            </asp:SqlDataSource>
        </form>
    </div>
</body>
</html>
